# Generated by Django 4.2.5 on 2023-10-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillogs',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failure', 'Ошибка')], max_length=10, verbose_name='статус попытки'),
        ),
    ]
