# Generated by Django 4.2.5 on 2023-10-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0002_alter_maillogs_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='mailing_name',
            field=models.CharField(default='Без имени', max_length=200, verbose_name='название рассылки'),
        ),
    ]
