# Generated by Django 4.2.5 on 2023-10-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0004_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='mailing_name',
            field=models.CharField(max_length=200, verbose_name='название рассылки'),
        ),
    ]
