# Generated by Django 4.2.5 on 2023-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0009_mailing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('running', 'Запущена')], default='created', max_length=10, verbose_name='статус рассылки'),
        ),
    ]
