# Generated by Django 4.2.5 on 2023-10-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_service', '0010_alter_mailing_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('-id',), 'permissions': [('change_activity', 'Change activity')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
